#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["pyyaml"]
# ///
"""Regenerate content/review/index.md from the current issue files."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml


def split_frontmatter(text: str) -> dict | None:
    if not text.startswith("---\n"):
        return None
    rest = text[4:]
    parts = rest.split("\n---\n", 1)
    if len(parts) < 2:
        return None
    try:
        return yaml.safe_load(parts[0]) or {}
    except yaml.YAMLError:
        return None


def read_issue(path: Path) -> dict | None:
    return split_frontmatter(path.read_text(encoding="utf-8"))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Regenerate review index.")
    parser.add_argument("issues_dir", type=Path, help="Path to content/review/issues/")
    parser.add_argument("index_path", type=Path, help="Path to content/review/index.md")
    args = parser.parse_args(argv)

    if not args.issues_dir.is_dir():
        print(f"Error: not a directory: {args.issues_dir}", file=sys.stderr)
        return 1

    issues: dict[str, list[dict]] = {"open": [], "fixed": [], "invalid": []}
    for path in sorted(args.issues_dir.glob("*.md")):
        if path.name == ".gitkeep":
            continue
        frontmatter = read_issue(path)
        if frontmatter is None:
            continue
        status = frontmatter.get("issue_status", "open")
        issues.setdefault(status, []).append(
            {
                "id": frontmatter.get("id", path.stem),
                "title": frontmatter.get("title", "Untitled"),
                "severity": frontmatter.get("severity", "unknown"),
                "tags": frontmatter.get("tags", []),
                "path": f"review/issues/{path.name}",
            }
        )

    # Reports are named YYYY-MM-DD-HHMM.md, so reverse-lexicographic
    # filename order is newest-first. A no-HHMM filename would sort after
    # a same-day HHMM one and break this; the report writer must use HHMM.
    reports_dir = args.issues_dir.parent / "reports"
    reports: list[dict] = []
    if reports_dir.is_dir():
        for path in sorted(reports_dir.glob("*.md"), reverse=True):
            if path.name == ".gitkeep":
                continue
            fm = read_issue(path)
            reports.append({
                "title": fm.get("title", "Untitled") if fm else "Untitled",
                "created": fm.get("created", "") if fm else "",
                "path": f"review/reports/{path.name}",
            })

    lines = [
        "---",
        "title: Automated icon4py review tracker",
        "---",
        "",
        "<!-- This file is auto-generated by scripts/icon4py-review/update-index.py. Edits will be overwritten. -->",
        "",
        "This page tracks automated review findings for C2SM/icon4py. "
        "Individual issue files live in `review/issues/`. "
        "Weekly overview reports live in `review/reports/`.",
        "",
    ]

    for status in ("open", "fixed", "invalid"):
        lines.append(f"## {status.capitalize()} issues")
        lines.append("")
        if not issues[status]:
            lines.append(f"_No {status} issues._")
            lines.append("")
            continue
        for issue in issues[status]:
            tags = ", ".join(issue["tags"]) if issue["tags"] else "none"
            lines.append(
                f"- [[{issue['path']}|{issue['title']}]] "
                f"- severity: {issue['severity']}, tags: {tags}"
            )
        lines.append("")

    lines.append("## Reports")
    lines.append("")
    if not reports:
        lines.append("_No reports._")
    else:
        for r in reports:
            lines.append(f"- [[{r['path']}|{r['title']}]]")
    lines.append("")

    args.index_path.parent.mkdir(parents=True, exist_ok=True)
    args.index_path.write_text("\n".join(lines), encoding="utf-8")
    total = sum(len(v) for v in issues.values())
    print(f"Wrote {args.index_path} with {total} issue(s) and {len(reports)} report(s).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
